server:
port: 81

spring:
datasource:
driver-class-name:  com.mysql.cj.jdbc.Driver
url: jdbc:mysql://43.139.138.145:3306/phoenix?useSSL=false&serverTimezone=UTC
username: phoenix
password: 1724298148

mybatis-plus:
global-config:
db-config:
table-prefix: tb1_
id-type: auto
configuration:
log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
